# As the orchestration need is simple to declare,
# Service and ReplicationController yamls files are combined.
apiVersion: v1
kind: ReplicationController
metadata:
  name: productcatalogue-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - image: eu.gcr.io/refined-algebra-215620/productcatalogue:v1
        imagePullPolicy: Always
        name: productcatalogue
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 8083
          name: http-server
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          periodSeconds: 2
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  namespace: default
  labels:
    app: productcatalogue
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: productcatalogue